service: sls-nodejs-ts
plugins:
  - serverless-plugin-typescript
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x

package:
  exclude:
    - node_modules/**/*
  include:
    handler.ts

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
